import Fastify from 'fastify';
import cors from '@fastify/cors';
import jwt from '@fastify/jwt';
import rateLimit from '@fastify/rate-limit';
import bcrypt from 'bcryptjs';
import pg from 'pg';
import 'dotenv/config';
import { assertPaymentSignature, verifyWebhookSignature } from './payments.js';

const { Pool } = pg;
const app = Fastify({ logger: true, trustProxy: true });
const pool = new Pool({ connectionString: process.env.DATABASE_URL, max: Number(process.env.DB_POOL_MAX || 10), idleTimeoutMillis: 30000, connectionTimeoutMillis: 10000, ssl: process.env.DATABASE_SSL === 'true' ? { rejectUnauthorized: false } : undefined });
if (!process.env.DATABASE_URL || !process.env.JWT_SECRET) throw new Error('DATABASE_URL and JWT_SECRET are required');
await app.register(cors, { origin: process.env.CORS_ORIGIN ? process.env.CORS_ORIGIN.split(',').map(x=>x.trim()) : false, credentials:true });
await app.register(jwt, { secret:process.env.JWT_SECRET });
await app.register(rateLimit, { max:Number(process.env.RATE_LIMIT_MAX||120), timeWindow:'1 minute' });
const query=(text,params)=>pool.query(text,params);
const auth=async(req,reply)=>{try{await req.jwtVerify();}catch{return reply.code(401).send({error:'Unauthorized'});}};
const admin=async(req,reply)=>{await auth(req,reply);if(reply.sent)return;if(req.user.role!=='admin')return reply.code(403).send({error:'Admin only'});};
const cleanEmail=e=>String(e||'').trim().toLowerCase();
const publicStudent=s=>({id:s.id,name:s.name,email:s.email,grade:s.grade});
const plans={pro_pass:{title:'Class Pro Pass',amount:499},master_pass:{title:'All-Access Master',amount:1499}};

app.get('/health',async(_req,reply)=>{try{await query('SELECT 1');return{status:'ok',service:'a2z-learning-api',database:'ok'};}catch{return reply.code(503).send({status:'degraded',service:'a2z-learning-api',database:'unavailable'});}});
app.get('/ready',async(_req,reply)=>{try{await query('SELECT 1');return{ready:true};}catch{return reply.code(503).send({ready:false});}});

app.post('/api/auth/register',async(req,reply)=>{const{name,email,password,grade=6}=req.body||{};if(!name||!email||!password||password.length<8||!Number.isInteger(Number(grade))||Number(grade)<1||Number(grade)>12)return reply.code(400).send({error:'Valid name, email, password (8+ chars) and grade are required'});const passwordHash=await bcrypt.hash(password,12);try{const{rows}=await query('INSERT INTO students(name,email,password_hash,grade) VALUES($1,$2,$3,$4) RETURNING id,name,email,grade',[String(name).trim(),cleanEmail(email),passwordHash,Number(grade)]);const student=rows[0];return{student,token:app.jwt.sign({sub:student.id,role:'student'},{expiresIn:'7d'})};}catch(e){if(e.code==='23505')return reply.code(409).send({error:'Email already registered'});throw e;}});
app.post('/api/auth/login',async(req,reply)=>{const{email,password}=req.body||{};const{rows}=await query('SELECT * FROM students WHERE email=$1',[cleanEmail(email)]);const student=rows[0];if(!student||!(await bcrypt.compare(password||'',student.password_hash)))return reply.code(401).send({error:'Invalid credentials'});return{student:publicStudent(student),token:app.jwt.sign({sub:student.id,role:student.role||'student'},{expiresIn:'7d'})};});
app.get('/api/me',{preHandler:auth},async req=>{const{rows}=await query('SELECT id,name,email,grade,created_at FROM students WHERE id=$1',[req.user.sub]);return rows[0]||null;});
app.get('/api/chapters',async req=>{const grade=Number(req.query.grade||6),subject=String(req.query.subject||'science');const{rows}=await query('SELECT id,grade,subject,chapter_no,title,slug,summary,content_url,published FROM chapters WHERE grade=$1 AND subject=$2 AND published=true ORDER BY chapter_no',[grade,subject]);return rows;});
app.get('/api/chapters/:id',async req=>{const{rows}=await query('SELECT id,grade,subject,chapter_no,title,slug,summary,content_url,published FROM chapters WHERE id=$1 AND published=true',[req.params.id]);if(!rows[0])return reply.code(404).send({error:'Chapter not found'});return rows[0];});
app.post('/api/progress',{preHandler:auth},async(req,reply)=>{const{chapterId,status='started',score=null,timeSpentSeconds=0}=req.body||{};if(!chapterId||!['started','attempted','completed'].includes(status)||Number(timeSpentSeconds)<0)return reply.code(400).send({error:'Invalid progress payload'});const{rows}=await query(`INSERT INTO progress(student_id,chapter_id,status,best_score,time_spent_seconds,last_activity_at) VALUES($1,$2,$3,$4,$5,NOW()) ON CONFLICT(student_id,chapter_id) DO UPDATE SET status=CASE WHEN EXCLUDED.status='completed' THEN 'completed' ELSE progress.status END,best_score=GREATEST(progress.best_score,COALESCE(EXCLUDED.best_score,0)),time_spent_seconds=progress.time_spent_seconds+EXCLUDED.time_spent_seconds,last_activity_at=NOW() RETURNING *`,[req.user.sub,chapterId,status,score===null?0:Number(score),Number(timeSpentSeconds)]);return rows[0];});
app.get('/api/dashboard',{preHandler:auth},async req=>{const{rows}=await query(`SELECT c.id,c.grade,c.subject,c.chapter_no,c.title,COALESCE(p.status,'not_started') status,COALESCE(p.best_score,0) best_score,COALESCE(p.time_spent_seconds,0) time_spent_seconds,p.last_activity_at FROM chapters c LEFT JOIN progress p ON p.chapter_id=c.id AND p.student_id=$1 WHERE c.published=true ORDER BY c.grade,c.subject,c.chapter_no`,[req.user.sub]);const completed=rows.filter(x=>x.status==='completed').length,attempted=rows.filter(x=>Number(x.best_score)>0).length,averageScore=rows.length?Math.round(rows.reduce((s,x)=>s+Number(x.best_score),0)/rows.length):0;return{chapters:rows,stats:{total:rows.length,completed,attempted,averageScore}};});
app.post('/api/assessments/submit',{preHandler:auth},async(req,reply)=>{const{chapterId,answers=[],score,total,timeSpentSeconds=0}=req.body||{};if(!chapterId||!Array.isArray(answers)||!Number.isInteger(score)||!Number.isInteger(total)||total<=0||score<0||score>total)return reply.code(400).send({error:'Invalid assessment payload'});const percentage=Math.round(score/total*100),client=await pool.connect();try{await client.query('BEGIN');const a=await client.query('INSERT INTO assessment_attempts(student_id,chapter_id,score,total,percentage,answers,time_spent_seconds) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id,percentage,created_at',[req.user.sub,chapterId,score,total,percentage,JSON.stringify(answers),Number(timeSpentSeconds)]);await client.query(`INSERT INTO progress(student_id,chapter_id,status,best_score,time_spent_seconds,last_activity_at) VALUES($1,$2,$3,$4,$5,NOW()) ON CONFLICT(student_id,chapter_id) DO UPDATE SET status=CASE WHEN $3='completed' THEN 'completed' ELSE progress.status END,best_score=GREATEST(progress.best_score,$4),time_spent_seconds=progress.time_spent_seconds+$5,last_activity_at=NOW()`,[req.user.sub,chapterId,percentage>=60?'completed':'attempted',percentage,Number(timeSpentSeconds)]);await client.query('COMMIT');return{attempt:a.rows[0],passed:percentage>=60};}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}});
app.get('/api/analytics/overview',{preHandler:auth},async req=>{const{rows}=await query(`SELECT COUNT(*)::int attempts,COALESCE(ROUND(AVG(percentage),2),0) average_score,COALESCE(SUM(time_spent_seconds),0)::int time_spent_seconds,COUNT(DISTINCT chapter_id)::int chapters_attempted FROM assessment_attempts WHERE student_id=$1`,[req.user.sub]);return rows[0];});
app.get('/api/analytics/chapter/:id',{preHandler:auth},async req=>{const{rows}=await query('SELECT id,score,total,percentage,time_spent_seconds,created_at FROM assessment_attempts WHERE student_id=$1 AND chapter_id=$2 ORDER BY created_at DESC',[req.user.sub,req.params.id]);return rows;});

app.get('/api/access',{preHandler:auth},async req=>{const{rows}=await query(`SELECT id,plan,status,starts_at,ends_at FROM subscriptions WHERE student_id=$1 AND status='ACTIVE' AND (ends_at IS NULL OR ends_at>NOW()) ORDER BY ends_at DESC NULLS LAST`,[req.user.sub]);return{premium:rows.length>0,subscriptions:rows};});
app.get('/api/admin/revenue',{preHandler:admin},async()=>{const{rows}=await query(`SELECT COUNT(*)::int transactions,COALESCE(SUM(amount),0)::numeric revenue,COUNT(DISTINCT email)::int customers FROM payments WHERE status='SUCCESS'`);return rows[0];});
app.get('/api/admin/students',{preHandler:admin},async()=>{const{rows}=await query(`SELECT s.id,s.name,s.email,s.grade,s.created_at,COUNT(DISTINCT a.id)::int attempts,COALESCE(MAX(a.percentage),0)::int best_score FROM students s LEFT JOIN assessment_attempts a ON a.student_id=s.id GROUP BY s.id ORDER BY s.created_at DESC`);return rows;});

app.post('/api/payments/create-order',{preHandler:auth},async(req,reply)=>{const{planId,grade}=req.body||{},plan=plans[planId];if(!plan)return reply.code(400).send({error:'Invalid plan'});if(!process.env.RAZORPAY_KEY_ID||!process.env.RAZORPAY_KEY_SECRET)return reply.code(503).send({error:'Razorpay is not configured'});const authHeader=Buffer.from(`${process.env.RAZORPAY_KEY_ID}:${process.env.RAZORPAY_KEY_SECRET}`).toString('base64');const r=await fetch('https://api.razorpay.com/v1/orders',{method:'POST',headers:{Authorization:`Basic ${authHeader}`,'Content-Type':'application/json'},body:JSON.stringify({amount:plan.amount*100,currency:'INR',receipt:`a2z-${Date.now()}`,notes:{planId,grade:String(grade||req.user.grade)}})});if(!r.ok)return reply.code(502).send({error:'Unable to create Razorpay order'});const order=await r.json();const{rows}=await query('INSERT INTO payments(student_id,provider,provider_order_id,email,plan,grade,amount,currency,status,metadata) SELECT id,$2,$3,email,$4,$5,$6,$7,$8,$9 FROM students WHERE id=$1 RETURNING id',[req.user.sub,'razorpay',order.id,planId,Number(grade||6),plan.amount,'INR','PENDING',JSON.stringify(order)]);return{paymentId:rows[0].id,key:process.env.RAZORPAY_KEY_ID,orderId:order.id,amount:order.amount,currency:order.currency};});
app.post('/api/payments/verify',{preHandler:auth},async(req,reply)=>{const{razorpay_order_id,razorpay_payment_id,razorpay_signature}=req.body||{};if(!razorpay_order_id||!razorpay_payment_id||!razorpay_signature||!assertPaymentSignature(razorpay_order_id,razorpay_payment_id,razorpay_signature,process.env.RAZORPAY_KEY_SECRET))return reply.code(400).send({error:'Invalid payment signature'});const{rows}=await query('SELECT * FROM payments WHERE provider_order_id=$1 AND student_id=$2',[razorpay_order_id,req.user.sub]);const payment=rows[0];if(!payment)return reply.code(404).send({error:'Payment order not found'});if(payment.status==='SUCCESS')return{success:true};const client=await pool.connect();try{await client.query('BEGIN');const p=await client.query(`UPDATE payments SET provider_payment_id=$1,status='SUCCESS',updated_at=NOW() WHERE id=$2 AND status='PENDING' RETURNING *`,[razorpay_payment_id,payment.id]);if(!p.rows[0]){await client.query('ROLLBACK');return{success:true};}await client.query(`INSERT INTO subscriptions(student_id,email,plan,status,starts_at,ends_at,payment_id) VALUES($1,$2,$3,'ACTIVE',NOW(),NOW()+INTERVAL '1 year',$4)`,[req.user.sub,payment.email,payment.plan,payment.id]);await client.query('COMMIT');return{success:true,plan:payment.plan};}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}});
app.post('/api/payments/webhook',async(req,reply)=>{const signature=req.headers['x-razorpay-signature'];const raw=JSON.stringify(req.body);if(!verifyWebhookSignature(raw,signature,process.env.RAZORPAY_WEBHOOK_SECRET))return reply.code(400).send({error:'Invalid webhook signature'});if(req.body?.event==='payment.captured'){const p=req.body.payload?.payment?.entity;const{rows}=await query(`UPDATE payments SET provider_payment_id=COALESCE(provider_payment_id,$1),status='SUCCESS',updated_at=NOW() WHERE provider_order_id=$2 RETURNING *`,[p?.id,p?.order_id]);const payment=rows[0];if(payment){await query(`INSERT INTO subscriptions(student_id,email,plan,status,starts_at,ends_at,payment_id) VALUES($1,$2,$3,'ACTIVE',NOW(),NOW()+INTERVAL '1 year',$4) ON CONFLICT DO NOTHING`,[payment.student_id,payment.email,payment.plan,payment.id]);}}return{received:true};});

app.setErrorHandler((error,_req,reply)=>{app.log.error(error);reply.code(error.statusCode||500).send({error:error.statusCode?error.message:'Internal server error'});});
app.addHook('onClose',async()=>{await pool.end();});
const port=Number(process.env.PORT||4000);await app.listen({port,host:'0.0.0.0'});
